"""
Shared Pydantic models for the SIEM platform.

These models define the canonical data shapes that flow between services:

    RawLogMessage   -- sent by Ingestor to Redis stream "raw_logs"
    ECSEvent        -- emitted by Normalizer; persisted in `events` table;
                       sent to Redis stream "normalized_events"
    Incident        -- created by Correlation Engine via Alert Manager;
                       persisted in `incidents` table

The schema is a curated subset of the Elastic Common Schema (ECS),
"""

from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from typing import Any, Optional
from uuid import UUID, uuid4

from pydantic import BaseModel, Field, IPvAnyAddress, ConfigDict


# ============================================
# Enumerations
# ============================================

class LogSource(str, Enum):
    """Identifies which log source produced a raw message."""
    NGINX = "nginx"
    DEMO_WEBAPP = "demo-webapp"
    UNKNOWN = "unknown"


class LogFormat(str, Enum):
    """How the raw payload should be parsed by the Normalizer."""
    NGINX_COMBINED = "nginx_combined"
    JSON = "json"
    SYSLOG = "syslog"
    UNKNOWN = "unknown"


class EventCategory(str, Enum):
    """ECS event.category values used in this project."""
    AUTHENTICATION = "authentication"
    AUTHORIZATION = "authorization"
    WEB = "web"
    NETWORK = "network"


class EventOutcome(str, Enum):
    """ECS event.outcome values."""
    SUCCESS = "success"
    FAILURE = "failure"
    UNKNOWN = "unknown"


class IncidentSeverity(str, Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class IncidentStatus(str, Enum):
    OPEN = "open"
    ACKNOWLEDGED = "acknowledged"
    CLOSED = "closed"
    FALSE_POSITIVE = "false_positive"


# ============================================
# RawLogMessage
# ============================================

class RawLogMessage(BaseModel):
    """
    A raw, unparsed log line published by the Ingestor.

    The Normalizer reads these from Redis stream `raw_logs`.
    """
    model_config = ConfigDict(use_enum_values=True)

    message_id: UUID = Field(default_factory=uuid4)
    received_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    source: LogSource
    format: LogFormat

    # The raw payload, exactly as it came from the source
    payload: str

    # Optional: where it came from (file path, REST endpoint, etc.)
    origin: Optional[str] = None


# ============================================
# ECSEvent
# ============================================

class ECSEvent(BaseModel):
    """
    A normalized log event in ECS format.

    Mirrors the `events` table in PostgreSQL. Field names use snake_case
    while the canonical ECS uses dotted notation (e.g. `source.ip`); the
    mapping is straightforward and documented in the thesis.
    """
    model_config = ConfigDict(use_enum_values=True)

    id: UUID = Field(default_factory=uuid4)

    # ECS @timestamp -- when the event occurred at the source
    timestamp: datetime

    # ECS event.*
    event_category: EventCategory
    event_outcome: Optional[EventOutcome] = None
    event_action: Optional[str] = None

    # ECS source.*
    source_ip: Optional[IPvAnyAddress] = None
    source_port: Optional[int] = None

    # ECS user.*
    user_name: Optional[str] = None

    # ECS http.* and url.*
    http_method: Optional[str] = None
    url_path: Optional[str] = None
    http_response_status_code: Optional[int] = None
    user_agent: Optional[str] = None

    # Provenance
    log_source: LogSource

    # Original message for forensics
    raw_message: Optional[str] = None

    # Bookkeeping
    received_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


# ============================================
# Incident
# ============================================

class Incident(BaseModel):
    """
    An alert generated by a correlation rule.

    Mirrors the `incidents` table in PostgreSQL.
    """
    model_config = ConfigDict(use_enum_values=True)

    id: UUID = Field(default_factory=uuid4)

    rule_name: str
    rule_version: Optional[str] = None
    severity: IncidentSeverity

    first_event_at: datetime
    last_event_at: datetime
    detected_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    source_ip: Optional[IPvAnyAddress] = None
    target_user_name: Optional[str] = None

    event_count: int = Field(ge=1)

    details: Optional[dict[str, Any]] = None
    contributing_events: Optional[list[UUID]] = None

    status: IncidentStatus = IncidentStatus.OPEN
    notes: Optional[str] = None